### ISSUE TITLE
reflex-platform submodule??

### ISSUE THREAD

**Issue by gspia** [adamConnerSax/reflex-sumType-utilities#1]
Hi

After cloning, the reflex-platform dir was empty and first thought is that it is a git-submodule made with `git submodule add url-to-repo` or something similar.

If it were so, then the update of the submodule could be done with `git submodule foreach "(git checkout develop; git pull --recurse-submodules)&"` (to update the develop-branch of reflex-platform).

(It wasn't a submodule, so I had to rmdir the dir and then do it also with git, after which I made  the submodule.)

So, if possible, these would help / make the installation / easy up the path to try this lib

* Make the reflex-platform a git-submodule
* Add couple of lines instructions on how to update the submodule and how to nix-shell and build the project into the readme.md file. 

E.g.

```
After `git clone`, to install this library and build the example:
    git submodule foreach "(git checkout develop; git pull --recurse-submodules)&"
    nix-shell -A shells.ghc
    cabal new-build all
```

**Comment by adamConnerSax** [comment]
Huh.  I thought I had made it a submodule.  Sorry!  Fixed now.  And can't you just then do `git submodule init; git submodule update` after cloning?  I tried that and it worked.  So I added that to the readme since I don't understand if that foreach does the same thing.

**Comment by gspia** [comment]
Thanks for fixing this !
