### ISSUE TITLE
How to use/try the example?

### ISSUE THREAD

**Issue by gspia** [adamConnerSax/reflex-sumType-utilities#2]
Hi,

After compiling with `cabal new-build all`, it isn't immediately obvious, how to try the example. By trying out directly the executable, it gives an exception about opening a spawProcess (runInteractive process: exec: does not exist (No such file or directory).

After trying some wild guesses it seems that commenting the `spawnProcess` -line in the Main does the trick. Re-compile and the executable is directly runnable.

Anyhow, again to easy up the trials, the following might help a bit :

* comment that line (so that the exe doesn't crash) in the Main.hs
* a note into the readme.md that "find the executable, execute it, and point the browser to the localhost:port)

**Comment by adamConnerSax** [comment]
Thanks!  On my machine, the spawnProcess line opens a browser.  I didn't know that wouldn't work in general.  I'll add a comment.

**Comment by gspia** [comment]
Thanks for fixing & additional notes!
